# Generated by Django 4.2.2 on 2023-12-31 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0002_alter_parceria_data_realizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('bi', models.CharField(max_length=14, null=True)),
                ('contato1', models.IntegerField(null=True, verbose_name='Contato Principal')),
                ('contato2', models.IntegerField(null=True, verbose_name='Contato Alternativo')),
                ('imagem', models.ImageField(default='\\img\\img.jpg', upload_to='img/')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.bairro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('nif', models.CharField(max_length=14, null=True)),
                ('contato1', models.IntegerField(null=True, verbose_name='Contato Principal')),
                ('contato2', models.IntegerField(null=True, verbose_name='Contato Alternativo')),
                ('imagem', models.ImageField(default='\\img\\img.jpg', upload_to='img/')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.bairro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
