# Generated by Django 4.2.2 on 2023-12-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilloja',
            name='rua',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
