# Generated by Django 4.2.2 on 2023-12-31 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceria',
            name='data_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 3, 57, 46, 655178)),
        ),
    ]
