# Generated by Django 5.0.2 on 2024-03-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_perfilloja_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilloja',
            name='contato2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contato Alternativo'),
        ),
        migrations.AlterField(
            model_name='perfilparceiro',
            name='contato2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contato Alternativo'),
        ),
    ]
