# Generated by Django 4.2.2 on 2023-12-31 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_parceria_data_realizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceria',
            name='data_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 4, 44, 10, 165940)),
        ),
    ]
