# Generated by Django 4.2.2 on 2024-03-03 10:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0003_alter_parceria_data_realizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceria',
            name='data_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 11, 50, 44, 823994)),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='estado',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Efetuado', 'Efetuada')], default='Disponível', max_length=20, verbose_name='Estado da Parceria'),
        ),
        migrations.CreateModel(
            name='Parceria3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro1', models.CharField(default='Nenhum', help_text='Escreva o seu nome de usuário', max_length=100)),
                ('parceiro2', models.CharField(default='Nenhum', help_text='Escreva o seu nome de usuário', max_length=100)),
                ('parceiro3', models.CharField(default='Nenhum', help_text='Escreva o seu nome de usuário', max_length=100)),
                ('contato', models.IntegerField()),
                ('data_realizacao', models.DateTimeField(default=datetime.datetime(2024, 3, 3, 11, 50, 44, 824993))),
                ('estado', models.CharField(choices=[('Disponível', 'Disponível'), ('Efetuado', 'Efetuada')], default='Disponível', max_length=20, verbose_name='Estado da Parceria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parceria2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro1', models.CharField(default='Nenhum', help_text='Escreva o seu nome de usuário', max_length=100)),
                ('parceiro2', models.CharField(default='Nenhum', help_text='Escreva o seu nome de usuário', max_length=100)),
                ('contato', models.IntegerField()),
                ('data_realizacao', models.DateTimeField(default=datetime.datetime(2024, 3, 3, 11, 50, 44, 823994))),
                ('estado', models.CharField(choices=[('Disponível', 'Disponível'), ('Efetuado', 'Efetuada')], default='Disponível', max_length=20, verbose_name='Estado da Parceria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
